#!/bin/bash

jRunTool --funding_agency $AGENCY \
         --project $PROJECT \
         --round $ROUND \
         --application $APPLICATION \
         --dataset $DATASET \
         --cpu_count $CPU_COUNT \
         --scratch_dir $SCRATCH \
         --processed_dir $PROCESSED \
         --raw_pmactrace $RAW \
         --process

